# Generated by Django 6.0.6 on 2026-06-28 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='agents/headshots/')),
                ('title', models.CharField(default='Real Estate Agent', help_text="e.g. 'Senior Agent', 'Luxury Specialist'", max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=60)),
                ('is_active_agent', models.BooleanField(default=True, help_text='Inactive agents are hidden from public agent listings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-years_experience'],
            },
        ),
    ]
